<?php

namespace AppBundle\Repository;

/**
 * UserskillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserskillRepository extends \Doctrine\ORM\EntityRepository
{
}
