<?php

namespace AppBundle\Repository;

/**
 * UserphoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserphoneRepository extends \Doctrine\ORM\EntityRepository
{
}
