<?php

namespace AppBundle\Repository;

/**
 * UserinfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserinfoRepository extends \Doctrine\ORM\EntityRepository
{
}
